
logging.level.org.springframework=INFO

################### DataSource Configuration ##########################
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=rootroot

################### Hibernate Configuration ##########################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.javax.persistence.validation.mode=none

spring.security.oauth2.client.registration.github.client-id=Ov23lizjXmYHMs0HxFje
spring.security.oauth2.client.registration.github.client-secret=ed2c3e4ce57d2499cbe898c523ca8fbc4cc9f588

